name: Inputs and Outputs Demo

on:
  workflow_dispatch:
    inputs:
      user_name:
        description: "Name of the user"
        required: true
        default: "GitHubUser"
      user_message:
        description: "Custom message from the user"
        required: false
        default: "Hello from GitHub Actions!"

jobs:
  demo-job:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Use inputs and create output
      - name: Use Inputs and Generate Output
        id: step1
        run: |
          echo "Name: ${{ github.event.inputs.user_name }}"
          echo "Message: ${{ github.event.inputs.user_message }}"
          # Imposta un output
          echo "::set-output name=processed_name::Processed: ${{ github.event.inputs.user_name }}"

      # Step 2: Use previous step output
      - name: Use Output from Step 1
        run: |
          echo "Output from Step 1: ${{ steps.step1.outputs.processed_name }}"

  another-job:
    runs-on: ubuntu-latest
    needs: demo-job
    steps:
      # Step 3: Use shared job outputs
      - name: Use Output from Previous Job
        run: |
          echo "Output from Previous Job: ${{ needs.demo-job.outputs.processed_name }}"
