name: Inputs and Outputs Demo

on:
  workflow_dispatch:
    inputs:
      user_name:
        description: "Name of the user"
        required: true
        default: "GitHubUser"

jobs:
  demo-job:
    runs-on: ubuntu-latest
    outputs:
      processed_name: ${{ steps.step1.outputs.processed_name }}
    steps:
      - name: Use Inputs and Generate Output
        id: step1
        run: |
          echo "Processing user: ${{ github.event.inputs.user_name }}"
          # Scrivi l'output in un environment file
          echo "processed_name=Processed: ${{ github.event.inputs.user_name }}" >> $GITHUB_ENV

  another-job:
    runs-on: ubuntu-latest
    needs: demo-job
    steps:
      - name: Use Output from Previous Job
        run: |
          echo "Output from Previous Job: ${{ needs.demo-job.outputs.processed_name }}"
