name: "Webhook Event Example"

on:
  repository_dispatch:
    types:
      - webhook

jobs:
  respond-to-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Debug Payload
        run: echo '${{ toJson(github.event) }}'

      - name: Run a script
        run: |
          echo "Event of type: ${{ github.event.action }}"
