name: "Workflow Commands"

on: ['push']

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      
      - name: Group logging
        run: |
          echo "::group::My group message"
          echo "msg1"
          echo "msg2"
          echo "::endgroup::"
      
      - name: Step 1
        run: |
          echo "MY_VAR=hi mate" >> $GITHUB_ENV

      - name: Step 1
        run: |
          echo $MY_VAR